import { Entry } from "./types";

const fighter: Entry[] = [
  // Athlete
  {
    name: "Athlete",
    tags: ["Class", "+HP"],
    prerequisites:
      "Novice Athletics, One of Athletic Prowess, Mounted Prowess, Power Boost, Stamina, or Swimmer",
    frequency: "At-Will – Extended Action",
    effect:
      "After an hour of exercise, an Athlete may choose two different Stats besides HP; both of those stats become Trained Stats. The default State of Trained Stats is +1 Combat Stages instead of 0. An Athlete may have two Trained Stats at a time.",
    book: "Core",
    pageNum: 155,
  },
  {
    name: "Training Regime",
    tags: ["+HP"],
    prerequisites: "Athlete",
    frequency: "Static",
    effect:
      "You gain additional static bonuses based on your Trained Stats.\n\n»» Attack: You gain a +2 Bonus on Accuracy Checks to hit with Combat Maneuvers.\n\n»» Defense: You gain 5 Damage Reduction when Intercepting attacks.\n\n»» Special Attack: You may add half your Special Attack Stat to Damaging Athlete Moves. This does not stack with Twisted Power.\n\n»» Special Defense: You gain a +2 Bonus to Opposed Checks to resist Combat Maneuvers.\n\n»» Speed: When you Sprint, you double your Movement Capability instead of increasing by 50%.",
    book: "Core",
    pageNum: 155,
  },
  {
    name: "Coaching",
    tags: ["+HP"],
    prerequisites: "Training Regime",
    frequency: "1 AP – Free Action",
    trigger: "Your Pokémon makes a Combat Maneuver",
    effect:
      "Your Pokémon gains a bonus based on the type of Combat maneuver they are making. This Feature may be triggered once per Scene per Pokémon.\n\n»» Your Pokémon gains a +1d6 bonus to Opposed Acrobatics, Athletics, Combat, or Stealth Skill Checks.\n\n»» If your Pokémon was Sprinting, they double their Movement Capabilities instead of increasing by 50%.\n\n»» If your Pokémon was making an Attack of Opportunity, they automatically hit.\n\n»» You may also activate this Feature to let them Intercept for any Ally regardless of Loyalty, and they automatically succeed on the Skill Check to do so.",
    book: "Core",
    pageNum: 155,
  },
  {
    name: "Adrenaline Rush",
    tags: ["+HP"],
    prerequisites: "Athlete, Expert Athletics",
    frequency: "Daily x3 – Free Action",
    trigger: "You are lowered to half or your Maximum Hit Points or less",
    effect:
      "You gain +1 Combat Stage in each of your Trained Stats, are cured of up to two Status Afflictions, and gain a Tick of Temporary Hit Points. Adrenaline Rush may be used only once per Scene",
    book: "Core",
    pageNum: 155,
  },
  {
    name: "Athletic Moves",
    image: "",
    tags: ["+HP", "Ranked 3"],
    frequency: "Static",
    effect:
      "You learn two Athlete Moves marked with the Rank of this Feature you are taking or lower.",
    extraFields: {
      "Rank 1 Prerequisites": "Athlete",
      "Rank 2 Prerequisites": "Athlete, Expert Athletics",
      "Rank 3 Prerequisites": "Athlete, Master Athletics",
    },
    book: "Core",
    pageNum: 155,
  },
  // Dancer
  {
    name: "Dancer",
    tags: ["Class", "+Speed"],
    prerequisites: "Novice Acrobatics; Novice Athletics or Charm",
    frequency: "Static",
    effect: "Choose Spinning Dance or Own Tempo. You gain the chosen Ability.",
    book: "Core",
    pageNum: 157,
  },
  {
    name: "Dance Form",
    tags: ["+Speed"],
    prerequisites: "Dancer",
    frequency: "Static",
    effect:
      "Create and learn two Dance Moves, plus one more for each other Dancer Feature you have. Whenever you gain another Dancer Feature, create and learn another Dance Move.",
    seeAlso: ["Dance Moves"],
    book: "Core",
    pageNum: 157,
  },
  {
    name: "Beguiling Dance",
    tags: ["+Speed"],
    prerequisites: "Dance Form",
    frequency: "Static",
    effect:
      "When creating Dance Moves, you can choose to create a Dance Move that has Range: 4, 1 Target, AC 3, and lowers a Combat Stat (chosen at creation) by -2 Combat Stages. This Move is otherwise the same as other Dance Moves you could create except that Dance Moves created with this template have the Contest Effect Excitement instead of Get Ready!.",
    book: "Core",
    pageNum: 157,
  },
  {
    name: "Dance Practice",
    tags: ["+Speed"],
    prerequisites: "Dancer",
    frequency: "At-Will – Extended Action",
    target: "Your Pokémon with at least 2 Tutor Points",
    effect:
      "The target loses 2 Tutor Points and gains your choice of Spinning Dance or Own Tempo. Dance Practice may target a Pokémon only once.",
    book: "Core",
    pageNum: 157,
  },
  {
    name: "Choreographer",
    tags: ["+Speed"],
    prerequisites: "Dance Form; Adept Acrobatics, Athletics, or Charm",
    frequency: "At-Will – Extended Action",
    target: "Your Pokémon with at least 2 Tutor Points",
    effect:
      "The target loses 2 Tutor Point and learns a Dance Move created by yourself. Choreographer may target a Pokémon multiple times.",
    book: "Core",
    pageNum: 157,
  },
  {
    name: "Power Pirouette",
    tags: ["+Speed"],
    prerequisites: "Dance Form; Expert Acrobatics, Athletics, or Charm",
    frequency: "Scene x2 – Swift Action",
    trigger: "You perform a Dance Move",
    effect:
      "Choose one effect:\n\n»» All adjacent targets are Confused.\n\n»» You gain +1 Combat Stage to a Stat of your choice not raised by the triggering Move.\n\n»» Destroy all Hazards within 5 meters, and remove Leech Seed, Trapped, and Stuck from yourself.",
    book: "Core",
    pageNum: 157,
  },
  {
    name: "Passing Waltz",
    tags: ["+Speed"],
    prerequisites: "Dance Practice, Master Acrobatics, Athletics, or Charm",
    frequency: "1 AP – Free Action",
    trigger:
      "You or one of your Pokémon with Own Tempo or Spinning Dance uses a Dance Move",
    effect:
      "Choose an ally within 3 meters of the triggering target. That ally gains Combat Stages from the triggering Move instead of the user.",
    book: "Core",
    pageNum: 157,
  },
  // Hunter
  {
    name: "Hunter",
    tags: ["Class", "+Speed"],
    prerequisites: "Novice Survival, Novice Stealth",
    frequency: "Static",
    effect: "Choose Teamwork or Pack Hunt. You gain the Chosen Ability.",
    book: "Core",
    pageNum: 159,
  },
  {
    name: "Pack Tactics",
    tags: ["+Speed"],
    prerequisites: "Hunter",
    frequency: "At-Will - Extended Action",
    target: "Your Pokémon with at least 2 Tutor Points",
    effect:
      "The target loses 2 Tutor Points and gains the Pack Hunt or Teamwork Ability. You may only target a Pokémon with Pack Tactics only once.",
    book: "Core",
    pageNum: 159,
  },
  {
    name: "Surprise!",
    tags: ["+Speed"],
    prerequisites: "Hunter, Adept Stealth or Survival",
    frequency: "X AP – Swift Action",
    trigger:
      "You make an attack against a foe that does not anticipate an attack or is adjacent to your Pokémon with Pack Hunt or Teamwork",
    effect:
      "Make two attack rolls for the triggering action, and use the better result to finalize the attack. If both attacks would hit, the target is Flinched. Surprise! may be used only once per Scene per target. If the triggering attack was a Poké Ball, Hand Net, Weighted Net, Glue Cannon, or Struggle Attack, Surprise! costs 1 AP to activate; otherwise, it costs 2 AP.",
    book: "Core",
    pageNum: 159,
  },
  {
    name: "Hunter's Reflexes",
    tags: ["+Speed"],
    prerequisites: "Hunter, Adept Stealth or Survival",
    frequency: "Static",
    effect:
      "You and your Pokémon may make up to three Attacks of Opportunity each round, instead of only one. Additionally, your attacks always consider you to be adjacent to your target for the purposes of benefiting from your Pokémon’s Teamwork Ability, and count as Melee attacks for the purposes of triggering their Pack Hunt Ability.",
    book: "Core",
    pageNum: 159,
  },
  {
    name: "Finisher",
    tags: ["+Speed"],
    prerequisites: "Hunter, Adept Stealth, Adept Survival",
    frequency: "Static",
    effect:
      "You and your Pokémon gain a +5 bonus to Damage Rolls against Fainted, Flinched, Sleeping, Stuck, Slowed, Trapped, or Tripped targets.",
    book: "Core",
    pageNum: 159,
  },
  {
    name: "Don't Look Away",
    tags: ["+Speed"],
    prerequisites: "Pack Tactics, Adept Stealth, Adept Survival",
    frequency: "1 AP – Free Action",
    trigger:
      "You or your Pokémon with Pack Hunt or Teamwork hits with an Attack of Opportunity",
    effect:
      "The hit foe loses a Tick of Hit Points, and is Slowed for 1 round. Don’t Look Away may be triggered once per round.",
    book: "Core",
    pageNum: 159,
  },
  {
    name: "Pack Master",
    tags: ["+Speed"],
    prerequisites: "Pack Tactics, Expert Stealth, Expert Survival",
    frequency: "Static",
    effect:
      "For you and your Pokémon with Teamwork, Teamwork’s effect now reads “While you are adjacent to an opponent, allies targeting that opponent receive a +2 bonus to Accuracy Checks”. Whenever you or your Pokémon successfully hit a foe with Pack Hunt, they gain a +2 Bonus to Accuracy Rolls and a +5 Bonus to Damage Rolls against that foe until the end of their next turn.",
    book: "Core",
    pageNum: 159,
  },
  // Martial Artist
  {
    name: "Martial Artist",
    image: "",
    tags: ["Class", "+Martial Artist Tag"],
    prerequisites: "Basic Martial Arts, Novice Combat",
    frequency: "Static",
    effect:
      "Choose one of the listed abilities. You gain the chosen Ability and its associated tag. Whenever you gain any Martial Artist Feature, you also gain the associated tag.",
    book: "Core",
    pageNum: 161,
  },
  {
    name: "Martial Training",
    image: "",
    tags: ["Ranked 3", "+Martial Artist Tag"],
    frequency: "Static",
    effect:
      "Learn two Martial Artist Moves. You may choose any Move marked with the Martial Training Rank you are taking or lower. Moves marked with an Ability require that Ability to be chosen.",
    extraFields: {
      "Rank 1 Prerequisites": "Martial Artist",
      "Rank 2 Prerequisites": "Martial Artist, Expert Combat",
      "Rank 3 Prerequisites": "Martial Artist, Master Combat",
    },
    book: "Core",
    pageNum: 161,
  },
  {
    name: "My Kung-Fu is Stronger",
    tags: ["+Martial Artist Tag"],
    prerequisites: "Martial Training Rank 1",
    frequency: "At-Will – Free Action",
    trigger: "A foe provokes an Attack of Opportunity",
    effect:
      "You may use Rock Smash instead of an unarmed Struggle Attack. If you do, Rock Smash’s Effect Range is increased by +2.",
    book: "Core",
    pageNum: 162,
  },
  {
    name: "Martial Achievement",
    tags: ["+Martial Artist Tag"],
    prerequisites: "Martial Artist",
    frequency: "Static",
    effect: "You gain a Martial Achievement based on your chosen Ability.",
    seeAlso: ["Martial Achievement List"],
    book: "Core",
    pageNum: 162,
  },
  {
    name: "Second Strike",
    tags: ["Special"],
    prerequisites: "Martial Training Rank 1, Expert Combat",
    frequency: "At-Will – Free Action",
    trigger:
      "You attempt to use a Grapple, Push, Trip, or Disarm Combat Maneuver but fail the Opposed Roll",
    effect:
      "You may immediately use Rock Smash or a Struggle Attack against your target as a Free Action.",
    book: "Core",
    pageNum: 162,
  },
  // Musician
  {
    name: "Musician",
    tags: ["Class", "+Special Attack"],
    prerequisites: "Novice Charm, Novice Focus",
    frequency: "Static",
    effect: "You may use Musician Songs.",
    seeAlso: ["Song List"],
    book: "Core",
    pageNum: 164,
  },
  {
    name: "Musical Ability",
    tags: ["+Special Attack"],
    prerequisites: "Musician",
    frequency: "Static",
    effect: "Choose Drown Out or Soundproof. You gain the chosen Ability.",
    book: "Core",
    pageNum: 164,
  },
  {
    name: "Mt. Moon Blues",
    tags: ["+Special Attack"],
    prerequisites: "Musician",
    frequency: "Static",
    effect: "You learn the Moves Sing and Supersonic",
    book: "Core",
    pageNum: 164,
  },
  {
    name: "Cacophony",
    tags: ["+Special Attack"],
    prerequisites: "Mt. Moon Blues, Adept Charm or Focus",
    frequency: "Static",
    effect: "You learn the Moves Screech and Metal Sound.",
    book: "Core",
    pageNum: 164,
  },
  {
    name: "Noise Complaint",
    tags: ["+Special Attack"],
    prerequisites: "Cacophany, Expert Charm or Focus",
    frequency: "Static",
    effect: "You learn the Moves Uproar and Hyper Voice.",
    book: "Core",
    pageNum: 164,
  },
  {
    name: "Voice Lessons",
    tags: ["+Special Attack"],
    prerequisites: "Noise Complaint",
    frequency: "Static",
    effect:
      "You and your Pokémon’s Moves with the Sonic keyword gain the Friendly keyword. Voice Lessons may not affect the Move Perish Song. Additionally, whenever your Pokémon use a Move with the Sonic Keyword in a Contest, they may roll +1d6.",
    book: "Core",
    pageNum: 164,
  },
  {
    name: "Power Chord",
    prerequisites: "Noise Complaint, Master Charm or Focus",
    frequency: "Scene x2 – Free Action",
    trigger: "You play a Song",
    effect:
      "Make a Charm or Focus Check, and add your Special Attack. Foes in the area of effect take Special Normal-Type Damage equal to the result.",
    book: "Core",
    pageNum: 164,
  },
  // Provocateur
  {
    name: "Provocateur",
    tags: ["Class", "+Speed"],
    prerequisites:
      "One of Confidence Artist, Intimidating Presence, or Charmer",
    frequency: "Static",
    effect: "You learn the Moves Sweet Kiss and Taunt.",
    note: "Provocateur Skills are Charm, Guile, and Intimidate.",
    book: "Core",
    pageNum: 166,
  },
  {
    name: "Push Buttons",
    tags: ["+Speed"],
    prerequisites: "Provocateur",
    frequency: "Static",
    effect:
      "Your Social Moves’ Frequency is not Expended if they miss. You gain the Demoralize Edge, even if you do not meet the prerequisites. Its effects for Status Moves now trigger on 18+, and Social Moves that activate this “Crit” Range cause their targets to lose a tick of Hit Points. If you already have Demoralize, you may gain another Edge for which you meet the prerequisites.",
    book: "Core",
    pageNum: 166,
  },
  {
    name: "Quick Wit",
    tags: ["+Speed"],
    prerequisites: "Provocateur, a Provocateur Skill at Adept Rank",
    frequency: "Scene x3 – Swift Action",
    effect:
      "You may make a Manipulate Maneuver or use a Social Move you know, Frequency allowing.",
    book: "Core",
    pageNum: 166,
  },
  {
    name: "Mixed Messages",
    tags: ["+Speed"],
    prerequisites: "Provocateur, two Provocateur Skills at Adept Rank",
    frequency: "Static",
    effect: "You learn the Moves Lovely Kiss and Torment.",
    book: "Core",
    pageNum: 166,
  },
  {
    name: "Powerful Motivator",
    tags: ["+Speed"],
    prerequisites: "Provocateur, two Provocateur Skills at Adept Rank",
    frequency: "Static",
    effect:
      "Baby-Doll Eyes, Confide, Leer, and your Provocateur Moves gain additional effects. These effects occur whether the Move hits or misses.\n\n»» Baby-Doll Eyes: The target cannot Critically Strike for 1 full round.\n\n»» Confide: The target cannot trigger Effect Ranges for 1 full round.\n\n»» Leer: The target is Slowed for 1 Full Round.\n\n»» Sweet Kiss: The target gains a -3 penalty to Evasion for 1 full round.\n\n»» Taunt: The target gains a -3 penalty to Accuracy Rolls 1 full round.\n\n»» Torment: The target gains a -10 penalty to Damage Rolls against your allies for 1 full round.\n\n»» Lovely Kiss: The target gains a -3 penalty to Save Checks for 1 full round.",
    book: "Core",
    pageNum: 166,
  },
  {
    name: "Play Them Like a Fiddle",
    tags: ["+Speed"],
    prerequisites: "Powerful Motivator, a Provocateur Skill at Expert Rank",
    frequency: "Scene x3 – Swift Action",
    trigger:
      "You hit with Leer, Confide, Baby-Doll Eyes, or a Provocateur Move",
    effect:
      "The Move gains additional effects as listed below. You may use the effects of each Move only once per Scene.\n\n»» Baby-Doll Eyes: The target becomes Infatuated with you for the rest of the Scene, and cannot be cured of this condition by any means, including Taking a Breather. This does not bypass immunity to Infatuation.\n\n»» Confide: You choose a Move the target has used this Scene. That Move becomes Disabled for the target.\n\n»» Leer: The target’s Defense is lowered an additional Combat Stage, and their Special Defense is lowered by 2 Combat Stages.\n\n»» Sweet Kiss: While the target is Confused, they may not perform Disengage Maneuvers, and whenever they hit themselves in Confusion, they provoke an Attack of Opportunity from all of their adjacent foes.\n\n»» Taunt: For 1 full round, the next damaging attack to hit the target of Taunt deals +3d8+10 Damage.\n\n»» Torment: The target’s Ability is disabled until the end of the encounter. If the target has more than one Ability, you choose one of them to disable.\n\n»» Lovely Kiss: The target’s Evasion is lowered by 2 for the rest of the Scene.",
    book: "Core",
    pageNum: 167,
  },
  {
    name: "Enchanting Gaze",
    tags: ["+Speed"],
    prerequisites: "Quick Wit, two Provocateur Skills at Expert Rank",
    frequency: "2 AP – Standard Action",
    effect:
      "Choose a Manipulate Maneuver effect; apply that Effect to all foes in a Cone 2. This ignores Frequency Limitations with that Maneuver and automatically succeeds against all targets without an opposed roll.",
    book: "Core",
    pageNum: 167,
  },
  // Rogue
  {
    name: "Rogue",
    tags: ["Class", "+Attack"],
    prerequisites: "Two of Acrobatics, Athletics, or Stealth at Novice Rank",
    frequency: "Static",
    effect: "You learn the Moves Feint Attack and Thief.",
    note: "Rogue Skills are Acrobatics, Athletics, and Stealth.",
    book: "Core",
    pageNum: 169,
  },
  {
    name: "Cutthroat",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Rogue",
    frequency: "Static",
    effect:
      "You may use Rogue Moves as Weapon Moves when wielding Small Melee Weapons or Short Ranged Weapons. If you do, Rogue Moves instead have the same Range as your Weapon. Additionally, you may qualify for Weapon Moves for Small Melee or Short Ranged Weapons and resist Disarm Maneuvers when wielding such Weapons using any Rogue Skill.",
    book: "Core",
    pageNum: 169,
  },
  {
    name: "Dirty Fighting",
    tags: ["+Attack"],
    prerequisites: "Rogue, a Rogue Skill at Adept Rank",
    frequency: "1 AP – Swift Action",
    trigger: "You hit a foe with Weapon Attack",
    effect:
      "After the attack is Resolved, you may immediately use the Dirty Trick Maneuver if the target is within range. You automatically hit with Dirty Trick, but must still make an Opposed Roll.",
    book: "Core",
    pageNum: 169,
  },
  {
    name: "Unexpected Attacks",
    tags: ["+Attack"],
    prerequisites: "Rogue, two Rogue Skills at Adept Rank",
    frequency: "Static",
    effect: "You learn the Moves Pursuit and Sucker Punch.",
    book: "Core",
    pageNum: 169,
  },
  {
    name: "Underhanded Tactics",
    tags: ["+Attack"],
    prerequisites: "Rogue, a Rogue Skill at Expert Rank",
    frequency: "Static",
    effect: "You gain your choice of Ambush or Cruelty.",
    book: "Core",
    pageNum: 169,
  },
  {
    name: "Street Fighter",
    tags: ["+Attack"],
    prerequisites: "Unexpected Attacks, two Rogue Skills at Expert Rank",
    frequency: "Static",
    effect: "You learn the Moves Assurance and Payback.",
    book: "Core",
    pageNum: 169,
  },
  {
    name: "Scoundrel's Strike",
    tags: ["+Attack"],
    prerequisites: "Underhanded Tactics, Street Fighter",
    frequency: "Daily x3 – Swift Action",
    trigger: "You hit with a Rogue Move",
    effect:
      "The target loses Hit Points equal to your highest Rogue Skill Rank doubled, and an additional effect based on whether you have the Ambush or Cruelty Ability. You may use Scoundrel’s Strike only once per Scene per target.\n\n»» Ambush: For 1 Full Round, the target is Slowed, cannot make Attacks of Opportunity, and takes a -2 penalty to all rolls.\n\n»» Cruelty: For 1 Full Round, the target loses 5 Hit Points upon being hit by any damaging attack.",
    book: "Core",
    pageNum: 169,
  },
  // Roughneck
  {
    name: "Roughneck",
    tags: ["Class", "+Defense"],
    prerequisites: "Novice Athletics, Intimidating Presence",
    frequency: "1 AP – Swift Action",
    trigger: "You hit a foe with an Attack",
    effect: "The foe loses a Combat Stage in the Stat of your choice.",
    book: "Core",
    pageNum: 171,
  },
  {
    name: "Menace",
    tags: ["+Defense"],
    prerequisites: "Roughneck",
    frequency: "At-Will – Swift Action",
    trigger: "You hit a foe with the Terrorize Manipulation",
    effect:
      "Until their next turn, the target has their Initiative lowered to 0. For one full round, attacks against them cause them to Flinch on 17+ or have their existing Flinch Range increased by +4.",
    book: "Core",
    pageNum: 171,
  },
  {
    name: "Mettle",
    tags: ["+Defense"],
    prerequisites: "Roughneck",
    frequency: "Scene x2 – Free Action",
    target: "You take Massive Damage or Intercept a Damaging Attack.",
    effect:
      "Resolve Damage as if the triggering attack was resisted one step. The triggering foe then loses 2 Combat Stages in the Attack Stat used by the triggering Attack.",
    book: "Core",
    pageNum: 171,
  },
  {
    name: "Malice",
    tags: ["+Defense"],
    prerequisites: "Roughneck, Adept Intimidate",
    frequency: "Static",
    effect: "You learn the Moves Mean Look and Chip Away.",
    book: "Core",
    pageNum: 171,
  },
  {
    name: "Fearsome Display",
    tags: ["+Defense"],
    prerequisites: "Malice",
    frequency: "2 AP – Swift Action ",
    trigger: "You use Leer or a Roughneck Move",
    effect:
      "The Move gains additional effects.\n\n»» Leer: Attacks against affected foes gain a +2 Bonus to their Critical Range for one full round.\n\n»» Chip Away: The target is considered Vulnerable against this attack.\n\n»» Headbutt: The target has their Initiative set to 0 until the end of their next turn.\n\n»» Glare: The target loses 2 Speed Combat Stages. This occurs whether Glare hits or misses.\n\n»» Mean Look: The target is Suppressed.\n\n»» Endure: You gain two Ticks of Temporary Hit Points.\n\n»» Slack Off: You are cured of one Status Affliction.",
    book: "Core",
    pageNum: 171,
  },
  {
    name: "Cruel Gaze",
    tags: ["+Defense"],
    prerequisites: "Roughneck, Expert Intimidate",
    frequency: "Static",
    effect: "You learn the Moves Glare and Headbutt.",
    book: "Core",
    pageNum: 171,
  },
  {
    name: "Tough as Nails",
    tags: ["+Defense"],
    prerequisites: "3 Roughneck Features, Master Intimidate",
    frequency: "Static",
    effect: "You learn the Moves Endure and Slack Off.",
    book: "Core",
    pageNum: 171,
  },
  // Tumbler
  {
    name: "Tumbler",
    tags: ["Class", "+Speed"],
    prerequisites: "Acrobat",
    frequency: "Static",
    effect: "You gain the Run Away Ability.",
    book: "Core",
    pageNum: 173,
  },
  {
    name: "Aerialist",
    tags: ["+Speed"],
    prerequisites: "Tumbler",
    frequency: "Static",
    effect: "You learn the Moves Aerial Ace and Splash.",
    book: "Core",
    pageNum: 173,
  },
  {
    name: "Quick Gymnastics",
    tags: ["+Speed"],
    prerequisites: "Tumbler",
    frequency: "1 AP – Free Action",
    trigger:
      "You hit with an Attack; you make a Jump; or you stand up from being Tripped",
    effect:
      "You may may Shift 2 Meters. You don’t count as Flanked or trigger Attacks of Opportunity until the end of your next turn. Additionally, if you activate this Feature, the triggering action does not provoke Attacks of Opportunity.",
    book: "Core",
    pageNum: 173,
  },
  {
    name: "Flip Out",
    tags: ["+Speed"],
    prerequisites: "Aerialist, Adept Acrobatics",
    frequency: "Static",
    effect:
      "Your Tumbler Moves gain additional effects.\n\n»» Aerial Ace: If you choose not to test for a Critical Hit, Aerial Ace gains the Pass Keyword.\n\n»» Splash: Once a Scene, you may use Splash as if it had the Interrupt keyword upon getting hit with an attack. If you do, you gain Damage Reduction against that attack equal to twice your Acrobatics Rank.\n\n»» Acrobatics: You may activate Acrobatics’s extra damage even while holding an Item.\n\n»» Bounce: When you use Bounce, you don’t trigger Hazards that turn and may choose to destroy all Hazards in your landing square and adjacent squares.",
    book: "Core",
    pageNum: 173,
  },
  {
    name: "Death From Above",
    tags: ["+Speed"],
    prerequisites: "Aerialist, Expert Acrobatics",
    frequency: "Static",
    effect: "You learn the Moves Acrobatics and Bounce.",
    book: "Core",
    pageNum: 173,
  },
  {
    name: "Quick Reflexes",
    tags: ["+Speed"],
    prerequisites: "Tumbler, Expert Acrobatics",
    frequency: "Static",
    effect: "You gain the Dodge Ability.",
    book: "Core",
    pageNum: 173,
  },
  {
    name: "Burst of Speed",
    tags: ["+Speed"],
    prerequisites: "5 Tumbler Features, Master Acrobatics",
    frequency: "Scene – Free Action",
    trigger: "You end your turn",
    effect:
      "Select an Initiative Count equal to half of your own Initiative or less; you may take an extra turn at that point in the round.",
    book: "Core",
    pageNum: 173,
  },
];

export default fighter;
