import { Entry } from "./types";

const got: Entry[] = [
  {
    name: "Arcane Training",
    tags: ["+Special Attack", "Weapon"],
    prerequisites:
      "Novice Occult Education, Elemental Connection or Mystic Senses",
    frequency: "Static",
    effect:
      "You may use Arcane Weapons. Attacks made with your Arcane Weapons share the Type of your Elemental Connection. If you have Mystic Senses, these Attacks deal Normal Type Damage. Arcane Weapon users that qualified through Mystic Senses or Elemental Connection (Normal) gain a +5 Bonus to Damage Rolls and a +2 Bonus to Effect Range when using Arcane Weapon Attacks. When wielding an Arcane Weapon, you may resist Disarm Maneuvers with your Occult Education.",
    book: "GoT",
    pageNum: 47,
  },
  {
    name: "Smith",
    tags: ["Ranked 2", "+Attack"],
    frequency: "Static",
    effect:
      "Rank 1 Effect: You may create Simple Weapons for $1000, Light Shields for $1,500, and Light Armor for $4,000.\n\nRank 2 Effect: You may create Fine Weapons for $2,000, Helmets for $1,125, Heavy Shields for $2,250 and Heavy Armor for $5,000.",
    extraFields: {
      "Rank 1 Prerequisites": "Novice Focus, Novice Athletics",
      "Rank 2 Prerequisites": "Adept Focus, Adept Athletics",
    },
    note: "Work with your Game Master to determine what moves are on the Simple and Fine Weapons you create.",
    book: "GoT",
    pageNum: 47,
  },
  // Berserker
  {
    name: "Berserker",
    tags: ["Class", "+HP", "Weapon"],
    prerequisites: "Novice Combat, Novice Intimidate",
    frequency: "Static",
    effect:
      "You learn the Moves Rage and Flail. You may use these moves as a Weapon Attack when wielding Melee Weapons.",
    book: "GoT",
    pageNum: 49,
  },
  {
    name: "Power of Rage",
    tags: ["+HP"],
    prerequisites: "Berserker",
    frequency: "Static",
    effect: "Choose Enduring Rage or White Flame. You gain the chosen Ability.",
    book: "GoT",
    pageNum: 49,
  },
  {
    name: "Lessons In Rage & Pain",
    tags: ["+HP"],
    prerequisites: "Berserker, Adept Intimidate",
    frequency: "Static",
    effect:
      "While you have at least 1 Injury, add +X to your Damage Rolls with Rage, Flail, Fury Swipes, Thrash, and Weapon Attacks. X is equal to your Intimidate Rank plus the number of Injuries you have. You do not lose Hit Points from being Heavily Injured, and Injuries beyond the 5th do not lower your Maximum Hit Points.",
    book: "GoT",
    pageNum: 49,
  },
  {
    name: "Frenzy",
    tags: ["+HP"],
    prerequisites: "Berserker, Adept Combat",
    frequency: "Scene x2 – Free Action",
    effect:
      "You may immediately take your turn with Priority. If you do, you are instantly cured of Slowed and Stuck, and for the rest of this turn gain a +2 Bonus to Critical Hit Range, +2 Bonus to Movement Speed, and +2 Bonus to Acrobatics, Athletics, Combat, and Intimidate Checks.",
    extraFields: { Condition: "You must be Enraged to use this Feature" },
    book: "GoT",
    pageNum: 49,
  },
  {
    name: "Fight On and On",
    tags: ["+HP"],
    prerequisites: "Lessons in Rage & Pain, Adept Combat",
    frequency: "Daily – Free Action",
    trigger: "Your Hit Points are lowered to or below 0 while Enraged.",
    effect:
      "You are not Fainted; you instead Faint upon reaching -50% of your Max Hit Points. If you have 5 or more injuries, you may use this Feature regardless of Frequency.",
    book: "GoT",
    pageNum: 49,
  },
  {
    name: "Crash and Smash",
    tags: ["+HP", "Weapon"],
    prerequisites: "Frenzy, Expert Combat",
    frequency: "Static",
    effect:
      "You learn the Moves Double Edge and Thrash. You may use these moves as a Weapon Attack when wielding Melee Weapons.",
    book: "GoT",
    pageNum: 49,
  },
  {
    name: "Push it to the Limit",
    tags: ["+HP"],
    prerequisites: "Lessons in Rage & Pain, Expert Intimidate",
    frequency: "At-Will – Free Action",
    trigger: "You hit with a Berserker Move or Weapon Attack",
    effect:
      "Immediately gain one Injury before resolving the triggering attack. You gain a Tick of Temporary Hit Points and may cure yourself of a Persistent Status Affliction. The triggering attack doubles your damage bonus from Lessons in Rage and Pain.",
    book: "GoT",
    pageNum: 49,
  },
  {
    name: "Rune Master",
    tags: ["Class", "+Attack or Special Attack"],
    prerequisites: "Own 2 Unown, Novice Occult Education",
    frequency: "Static",
    effect:
      "You gain the Gather Unown capability, and your Unown gain the Letter Press Capability. When using Gather Unown, you are treated as a level 20 Pokémon.",
    book: "GoT",
    pageNum: 51,
  },
  {
    name: "Hidden Power",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Rune Master",
    frequency: "Static",
    effect:
      "You learn the Move Hidden Power. Whenever you use Hidden Power, it may be either Physical or Special, adding the appropriate Attack Stat.",
    book: "GoT",
    pageNum: 51,
  },
  {
    name: "Rewrite",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Hidden Power",
    frequency: "Daily",
    target: "Self or a willing Pokémon with Hidden Power.",
    effect:
      "Reroll the Type for an instance of Hidden Power the target knows If you target an Unown, you may transform the target into a different letter.",
    book: "GoT",
    pageNum: 51,
  },
  {
    name: "Words of Power",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Adept Occult Education, Hidden Power",
    frequency: "Static",
    trigger: "You or your Pokémon use Hidden Power",
    effect:
      "Instead of a Burst, you may choose to have Hidden Power be a 1 Target Melee, 1 Target 6m, or Cone 2. Additionally, you and your Prime Unown always have STAB on Hidden Power as if you or they were of the same Type.",
    book: "GoT",
    pageNum: 51,
  },
  {
    name: "Glyph",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Rune Master",
    frequency: "At-Will – Extended Action",
    target: "Your Unown that is not part of a Prime Unown",
    effect:
      "You may set the target Unown against any flat surface, and turn the Unown into a glyph. Glyphs have HP equal to your Level, and no other stats. Glyphs last until they are destroyed or intentionally de-activated, at which time the Unown returns to Unown Space, disappearing forever. You may have a number of active Glyphs equal to your Occult Education Rank. When setting a Glyph, you may have the Glyphs be either visible or invisible, as you prefer. At any time, as a Standard Action, you may Channel any Glyph you have set down. This causes the Glyph’s eye to open and become visible if it was not. While you are channeling a Glyph, you are able to see through the Glyph, listen through it, and project your voice through it.",
    book: "GoT",
    pageNum: 51,
  },
  {
    name: "Alarm Runes",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Glyph",
    frequency: "Bind 1 AP – Standard Action",
    target: "A Glyph you have put down, regardless of distance",
    effect:
      "You give the Glyph a Trigger, which may be as vague or as precise as you like (i.e.: “If anyone enters the room”, “if James peeks in my diary”, “If a Torkoal uses Surf while I scream the word ‘Gelato’”). If the trigger is met within the Rune’s 30 meters, the Rune will become visible, and will begin screeching loudly, alerting anyone nearby. You are capable of hearing this screeching noise in your head, regardless of your current distance. Glyphs will remember their Triggers as long as the AP spent on the Feature is Bound. If you have the Explosive Runes or Sentry Runes Features, you may instruct this Glyph to automatically use the chosen Feature as a Free Action when it is triggered if you have the AP to spend. You may have only one Glyph use Explosive Runes per round, even if multiple Runes are triggered at the same time.",
    book: "GoT",
    pageNum: 51,
  },
  {
    name: "Explosive Runes",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Adept Occult Education, Glyph, Hidden Power",
    frequency: "1 AP – Standard Action",
    target: "A Glyph you have put down, regardless of distance",
    effect:
      "You may use Hidden Power, originating the attack from the location of the targeted Glyph. Use your own Stats and Hidden Power values to calculate damage. Using this Feature causes the Glyph to become visible and glow for a minute afterwards.",
    book: "GoT",
    pageNum: 52,
  },
  {
    name: "Sentry Runes",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Expert Occult Education, Explosive Runes, Hidden Power",
    frequency: "1 AP – Standard Action",
    target: "A Glyph you have put down, regardless of distance",
    effect:
      "The target Glyph becomes an Unown of your Trainer Level, its Stats allocated as you wish. This Unown knows a single instance of Hidden Power, identical to your own. The Glyph can fight on its own without needing you to command it. At the end of the encounter, or after 5 minutes, the Unown returns to Unown Space forever, destroying the Glyph. You may only have one Glyph active in this way at a time; if various Alarm Glyphs are triggered to become Sentries at the same time, only one does so; the others will do so once the previous one has been destroyed if the Trigger condition is still being met.",
    book: "GoT",
    pageNum: 52,
  },
  {
    name: "Arcanist",
    tags: ["Class", "+Special Attack"],
    prerequisites: "Arcane Training",
    frequency: "At-Will – Extended Action ",
    target: "An Arcane Weapon",
    effect:
      "You create a Soul Bond with the target Weapon. You may make a Soul Bond with only one weapon at a time. If you create a new Soul Bond, previously Soul Bound weapons lose the Bond. Soul Bound Weapons gain the following benefits:\n\n»» Increase the Damage Base and Effect Range of Struggle Attacks and Arcane Weapon Moves made with your Soul Bonded Weapon by +1 for each Occult Education Rank you have above Novice, up to a maximum of +3 at Master Rank.\n\n»» As a Shift Action, you may beckon your Soul Bonded Weapon to your hands if it is within 10 meters. If it is being held by someone else who does not want to let go of the weapon, make an Occult vs Athletics Opposed Check. If you win, they their lose grip on your Weapon and it flies to your hand as normal.",
    book: "GoT",
    pageNum: 54,
  },
  {
    name: "Metamagic",
    tags: ["+Special Attack"],
    prerequisites: "Arcanist, Adept Occult Education",
    frequency: "1 AP – Swift Action ",
    trigger: "You use a Special Move",
    effect: "You may apply a Rank 1 Power Manipulation to your attack.",
    seeAlso: ["Power Manipulation List"],
    book: "GoT",
    pageNum: 54,
  },
  {
    name: "Authentic Thaumaturgy",
    tags: ["+Special Attack"],
    prerequisites: "Arcanist, Expert Occult Education",
    frequency: "Scene x2 – Swift Action ",
    trigger: "You use a Special Move",
    effect: "You may apply a Rank 2 Power Manipulation to your attack.",
    seeAlso: ["Power Manipulation List"],
    book: "GoT",
    pageNum: 54,
  },
  {
    name: "Signature Manipulations",
    tags: ["Ranked 2", "+Special Attack"],
    frequency: "Static",
    effect:
      "Each Rank, select a Power Manipulation of the same Signature Manipulation Rank you are taking or lower.\n\n»» For Rank 1 Manipulations, this Manipulation may be used twice per Scene without spending AP to activate.\n\n»» For Rank 2 Manipulations, this Manipulation may be used once per Scene without activating Authentic Thaumaturgy’s Frequency.",
    extraFields: {
      "Rank 1 Prerequisites": "Metamagic",
      "Rank 2 Prerequisites": "Authentic Thaumaturgy",
    },
    book: "GoT",
    pageNum: 54,
  },
  {
    name: "Recoup Energy",
    tags: ["+Special Attack"],
    prerequisites: "Arcanist, Expert Occult Education",
    frequency: "Scene x2 – Free Action ",
    trigger: "Your Special Move misses all targets",
    effect:
      "You do not expend the Frequency of the triggering Move. If you applied a Power Manipulation to the triggering Move, you are refunded the AP for the Manipulation or do not expend the Frequency for it.",
    book: "GoT",
    pageNum: 54,
  },
  {
    name: "Soul Investment",
    tags: ["+Special Attack", "Weapon"],
    prerequisites: "Arcanist, Master Occult Education",
    frequency: "Bind 2 AP – Extended Action",
    target: "Your Soul Bonded Weapon",
    effect:
      "Choose one Novice and one Expert Arcane Weapon Move. Your Soul Bonded Weapon adds those Moves to your Move List as long as this Feature is Bound. You may only Bind one instance of this Feature at a time, and you may not have multiple instances of the same Move in your Move List.",
    book: "GoT",
    pageNum: 54,
  },
  {
    name: "Fortress",
    tags: ["Class", "+Defense", "Weapon"],
    prerequisites: "Novice Combat, Novice Focus",
    frequency: "At-Will – Free Action",
    trigger:
      "You target an enemy with a Struggle attack or Weapon Attack and end your turn adjacent to the target.",
    effect:
      "You Mark all targets of the attack until the end of your next turn. Marked foes take a penalty to Attack Rolls against any targets besides you equal to your Focus Rank. A Mark from a different source (such as a second Fortress or a Fighting Type Ace’s Pokémon) will overwrite your Mark.",
    book: "GoT",
    pageNum: 57,
  },
  {
    name: "Slow or Steady",
    tags: ["+Defense"],
    prerequisites: "Fortress",
    frequency: "Static",
    effect: "Choose Analytic or Battle Armor. You gain the chosen ability.",
    book: "GoT",
    pageNum: 57,
  },
  {
    name: "Stalwart Bastion",
    tags: ["+Defense"],
    prerequisites: "Fortress",
    frequency: "Bind 2 AP – Standard Action",
    effect:
      "While this Feature is Bound, you and all cardinally adjacent allies gain Damage Reduction equal to your Combat or Focus Rank.",
    book: "GoT",
    pageNum: 57,
  },
  {
    name: "Shield Bearer",
    tags: ["+Defense"],
    prerequisites: "Stalwart Bastion",
    frequency: "1 AP – Swift Action",
    effect:
      "You may immediately ready a Shield, and do not become Slowed as a result. You may choose to grant an adjacent Ally the Evasion and Damage Reduction bonuses from your shield instead of gaining them yourself, but these bonuses only apply as long as the ally remains adjacent to you. If you do and the ally Shifts, you may Shift alongside your ally as a Shift Action Interrupt. This cannot cause you to shift more than your normal Movement.",
    book: "GoT",
    pageNum: 57,
  },
  {
    name: "Wall of Iron",
    tags: ["+Defense"],
    prerequisites: "Fortress, Adept Combat or Focus",
    frequency: "Static",
    effect: "You learn the moves Iron Defense and Protect.",
    book: "GoT",
    pageNum: 57,
  },
  {
    name: "Guardian's Punishment",
    tags: ["+Defense"],
    prerequisites: "Fortress, Expert Combat or Focus",
    frequency: "Scene x2 – Swift Action ",
    trigger: "You hit a Marked Foe with a Damaging Weapon attack",
    effect:
      "Add your Defense Stat to the Damage Roll. The Marked Foe takes a penalty to Damage Rolls equal to your Combat or Focus Rank for 1 full round.",
    book: "GoT",
    pageNum: 57,
  },
  {
    name: "Unstoppable Will",
    tags: ["+Defense"],
    prerequisites: "Slow or Steady, Expert Combat or Focus",
    frequency: "Static",
    effect: "You gain the Discipline Ability.",
    book: "GoT",
    pageNum: 57,
  },
  {
    name: "Marksman",
    tags: ["Class", "+Attack", "Weapon"],
    prerequisites: "Novice Combat, Novice Perception",
    frequency: "Static",
    effect: "You gain the Sniper Ability.",
    book: "GoT",
    pageNum: 59,
  },
  {
    name: "Aiming Down The Sights",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Marksman",
    frequency: "At Will – Shift Action",
    effect:
      "Your next Weapon Attack with a long-range Weapon gains +2 to its Accuracy Roll and Critical Hit Range. This effect lasts until used or until the start of your next turn.",
    book: "GoT",
    pageNum: 59,
  },
  {
    name: "Double Shot",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Marksman, Adept Combat",
    frequency: "1 AP – Standard Action",
    effect:
      "You may make two Struggle Attacks with a -2 penalty to Accuracy, each targeting the same foe. If the first attack gains the benefit of Aiming Down the Sights or Clear Shot, the second attack also gains the same benefits for free.",
    book: "GoT",
    pageNum: 59,
  },
  {
    name: "Overwatch",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Marksman, Adept Perception or Combat",
    frequency: "At-Will – Standard Action",
    effect:
      "Create a Line X, and place a Blast 3 with at least three meters overlapping the Line’s area. X is equal to your Weapon’s Range. For one full round, if a foe moves in or out of that area, you may make a Ranged Weapon attack, Frequency allowing, against that foe as a Free Action. You may not attack a specific foe more than once per round this way. While this is in effect, if you Move from your current location, Overwatch’s effect is lost.",
    book: "GoT",
    pageNum: 59,
  },
  {
    name: "Clear Shot",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Marksman, Expert Perception or Combat",
    frequency: "Scene x2 – Swift Action",
    trigger:
      "You make a ranged Weapon Attack against a target with no other combatants or Rough or Blocking Terrain within 2 meters",
    effect:
      "The target is considered Vulnerable against this attack, and you increase your Critical Hit range by +4 for this attack.",
    book: "GoT",
    pageNum: 59,
  },
  {
    name: "Crippling Shot",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Marksman, Expert Perception or Combat",
    frequency: "2 AP – Full Action",
    effect:
      "Make a Ranged Struggle Attack attack with a -2 penalty to Accuracy. If you hit, the attack deals Damage as if it was resisted one step, but the target becomes Slowed, loses 1 Speed Combat Stage, and you initiate a Trip Maneuver against the target. You may use your Perception Skill to resolve the Opposed Check if you wish.",
    book: "GoT",
    pageNum: 59,
  },
  {
    name: "Dead-Eye Shot",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Marksman, Master Combat or Perception",
    frequency: "Scene x2 – Standard, Priority",
    effect:
      "Use of Dead-Eye Shot must be declared at the start of the round. Nothings happens at this time. At the end of the round, the user may use their Shift Action, and then make a Ranged Weapon Attack and roll twice for Accuracy. You may resolve the attack using either result, but if you choose to use the lower result and the attack hits, it is automatically a Critical Hit.",
    book: "GoT",
    pageNum: 59,
  },
  {
    name: "Skirmisher",
    tags: ["Class", "+Speed", "Weapon"],
    prerequisites: "Novice Combat, Novice Acrobatics",
    frequency: "Static",
    effect: "Choose Flutter or Vanguard. You gain the Chosen Ability.",
    book: "GoT",
    pageNum: 61,
  },
  {
    name: "Nimble Steps",
    tags: ["+Speed"],
    prerequisites: "Skirmisher",
    frequency: "Static",
    effect: "You may perform the Disengage Maneuver as a Swift Action.",
    book: "GoT",
    pageNum: 61,
  },
  {
    name: "Counter Stance",
    tags: ["+Speed"],
    prerequisites: "Skirmisher",
    frequency: "At-Will – Free Action – Interrupt",
    trigger: "An adjacent foe misses you with an attack",
    effect: "You perform an Attack of Opportunity against them.",
    book: "GoT",
    pageNum: 61,
  },
  {
    name: "Harrier",
    tags: ["+Speed"],
    prerequisites: "Skirmisher",
    frequency: "At-Will – Free Action",
    trigger: "You hit a foe with a damaging Attack",
    effect:
      "Until the end of your next turn, that foe is considered Flanked, is Slowed, and cannot take actions as Priority or Interrupt. Harrier may only be used on a foe once per Scene.",
    book: "GoT",
    pageNum: 61,
  },
  {
    name: "Weapon Finesse",
    tags: ["+Speed", "Weapon"],
    prerequisites: "Counter Stance, Adept Combat or Acrobatics",
    frequency: "2 AP – Swift Action",
    trigger: "You hit a foe with a Weapon Attack.",
    effect:
      "After the attack is resolved, you may immediately use a Disarm, Trip, or Push Maneuver against that foe as a Free Action. The Maneuver automatically hits, but you must still make an Opposed Roll.",
    book: "GoT",
    pageNum: 61,
  },
  {
    name: "Outmaneuver",
    tags: ["+Speed"],
    prerequisites: "Harrier, Adept Combat or Acrobatics",
    frequency: "Scene x3 – Free Action",
    trigger: "You use a damaging Attack",
    effect:
      "Add half your Evasion to your Accuracy Roll for the attack, and all foes hit by the attack have their Initiative reduced by your full Evasion value.",
    book: "GoT",
    pageNum: 61,
  },
  {
    name: "Swift Strikes",
    tags: ["+Speed", "Weapon"],
    prerequisites: "4 Skirmisher Features, Master Combat or Acrobatics",
    frequency: "1 AP – Standard Action",
    effect:
      "Use a Weapon Attack as if it had the Priority Keyword. If the Move already had the Priority Keyword, use it as if it had the Priority (Advanced) Keyword instead.",
    book: "GoT",
    pageNum: 61,
  },
  {
    name: "Swarmlord",
    image: "",
    tags: ["Class", "Special"],
    prerequisites:
      "Elemental Connection (Bug), Novice Survival, Novice Command",
    frequency: "Static",
    effect:
      "Your powers begin to take after either Arachnid's Embrace or Monarch's Embrace. Depending on your Embrace, you gain an Ability and Stat Tags. Whenever you gain a Swarmlord Feature, you gain the same Stat Tags.",
    book: "GoT",
    pageNum: 63,
  },
  {
    name: "How To Shoot Web",
    prerequisites: "Swarmlord",
    frequency: "Static",
    effect: "You gain the Threaded and Wallclimber Capabilities.",
    book: "GoT",
    pageNum: 63,
  },
  {
    name: "Broodlord",
    prerequisites: "Enhanced Embrace Rank 2, Expert Command or Survival",
    frequency: "Static",
    effect:
      "You gain the following Ability based on your Embrace.\n\nArachnid’s Embrace: Tinted Lens\n\nMonarch’s Embrace: Compound Eyes",
    book: "GoT",
    pageNum: 63,
  },
  {
    name: "Pheromone Markers",
    prerequisites: "Enhanced Embrace Rank 1",
    frequency: "1 AP – Free Action ",
    trigger: "You hit a foe with a damaging Bug-Type attack",
    effect:
      "The triggering foe gains 1 Pheromone Stack. Your Bug-Type attacks gain a +2 bonus to Accuracy Rolls and +1 Critical Hit range against foes for each Pheromone Stack they have. Once per Scene per foe, when they gain their third or higher Pheromone Stack, you may choose to roll 1d6. On a result of 1 or 2, the foe becomes Confused; on a result of 3 or 4 the foe becomes Suppressed; on a result of 5 or 6 the foe becomes Enraged.",
    book: "GoT",
    pageNum: 63,
  },
  {
    name: "Enhanced Embrace",
    image: "",
    tags: ["Ranked 3"],
    frequency: "Static",
    effect:
      "Learn two Moves from the list below at the Rank of Enhanced Embrace you are taking or lower. Moves marked with an Embrace require that Embrace to be chosen.",
    extraFields: {
      "Rank 1 Prerequisites": "Swarmlord",
      "Rank 2 Prerequisites": "Adept Command or Survival",
      "Rank 3 Prerequisites": "Expert Command or Survival",
    },
    book: "GoT",
    pageNum: 63,
  },
  {
    name: "Shade Caller",
    tags: ["Class", "+Attack or Special Attack"],
    prerequisites: "Elemental Connection (Dark), Novice Guile, Novice Stealth",
    frequency: "Static",
    effect: "You learn Faint Attack and Snarl.",
    book: "GoT",
    pageNum: 65,
  },
  {
    name: "Twisted Soul",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Shade Caller",
    frequency: "Static",
    effect: "You gain the Twisted Power Ability.",
    book: "GoT",
    pageNum: 65,
  },
  {
    name: "Living Shadow",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Shade Caller",
    frequency: "Static",
    effect:
      "Your own Shadow can attack others; you may have your Dark Type Moves originate from any Square adjacent to you. If you are fighting among complete darkness, you may have your Dark Type Moves originate from any square within X meters that is completely dark, where X is the higher of your Guile or Stealth Rank. Attacks originating from Living Shadow do not trigger effects that rely on being hit with a melee attack.",
    book: "GoT",
    pageNum: 65,
  },
  {
    name: "Sharpen Shadows",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Shade Caller, Expert Guile or Stealth",
    frequency: "Static",
    effect: "You learn Dark Pulse and Night Slash",
    book: "GoT",
    pageNum: 65,
  },
  {
    name: "Heart of Darkness",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Sharpen Shadows, Master Guile or Stealth",
    frequency: "Static",
    effect: "You learn Night Daze and Punishment",
    book: "GoT",
    pageNum: 65,
  },
  {
    name: "World of Darkness",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Shade Caller, Adept Guile or Stealth",
    frequency: "2 AP – Standard Action",
    effect:
      "You create a zone of Shifting Darkness in a Burst 2 around you, which persists until the end of the encounter. All targets without Darkvision attacking from or i nto the Shifting Darkness receive a -3 penalty to Accuracy. You may count Shifting Darkness as complete darkness for the purposes of activating your Living Shadow. As a Static effect, you also gain the Darkvision Capability.",
    book: "GoT",
    pageNum: 65,
  },
  {
    name: "Dark Soul",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Shade Caller, Master Guile or Stealth",
    frequency: "Static",
    effect: "Choose Shadow Tag or Super Luck. You gain the chosen Ability.",
    book: "GoT",
    pageNum: 65,
  },
  {
    name: "Herald of Pride",
    tags: ["Class", "+Attack", "Weapon"],
    prerequisites:
      "Elemental Connection (Dragon), Novice Command, Novice Intimidate",
    frequency: "Static",
    effect:
      "When wielding Melee Weapons, you may use Command or Intimidate instead of Combat to determine the Damage Base of your Struggle Attacks, to resist Disarm Maneuvers, and to qualify for a Weapon’s Moves. Your Weapon Attacks ignore Damage Reduction up to your Command or Intimidate Rank.",
    book: "GoT",
    pageNum: 67,
  },
  {
    name: "Noblesse Oblige",
    tags: ["+Attack"],
    prerequisites: "Herald of Pride",
    frequency: "Static",
    effect: "You gain the Regal Challenge Ability",
    book: "GoT",
    pageNum: 67,
  },
  {
    name: "Channel the Dragon's Spirit",
    tags: ["+Attack"],
    prerequisites: "Herald of Pride",
    frequency: "1 AP – Free Action ",
    trigger: "You use a Weapon Attack",
    effect:
      "You may have the triggering attack deal Dragon-Type Damage if you wish. On 18+, all targets can only use At-Will Frequency Moves for one full round",
    book: "GoT",
    pageNum: 67,
  },
  {
    name: "Bare the Dragon's Claws",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Herald of Pride, Adept Command or Intimidate",
    frequency: "Static",
    effect:
      "Your learn the Moves Dragon Claw and Dragon Tail. You may use these Moves as Weapon Attacks when wielding Melee Weapons.",
    book: "GoT",
    pageNum: 67,
  },
  {
    name: "Call the Dragon's Rage",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Bare the Dragon's Claws, Master Command or Intimidate",
    frequency: "Static",
    effect:
      "You learn the Moves Dragon Rush and Outrage. You may use these Moves as Weapon Attacks when wielding Melee Weapons.",
    book: "GoT",
    pageNum: 67,
  },
  {
    name: "Rouse the Dragon's Blood",
    tags: ["+Attack"],
    prerequisites: "Herald of Pride, Expert Command or Intimidate",
    frequency: "Scene x2 – Free Action ",
    trigger: "You suffer a Critical Hit or gain an Injury from a foe’s attack",
    effect:
      "For 1 full round, the next Herald of Pride Move you use against the triggering foe cannot miss, cannot be Intercepted, and effects that would cause it to miss cannot be activated against it.",
    book: "GoT",
    pageNum: 67,
  },
  {
    name: "Sovereignty",
    tags: ["+Attack"],
    prerequisites: "Herald of Pride, Expert Command or Intimidate",
    frequency: "Bind 2 AP – Standard Action ",
    effect:
      "Effect: While this Feature is bound, you gain a +2 Bonus to Save Checks against Volatile Status Afflictions, and a +2 Bonus to Opposed Checks when defending against being Disarmed, Grappled, Pushed, or Tripped.",
    book: "GoT",
    pageNum: 67,
  },
  {
    name: "Spark Master",
    tags: ["Class", "+Speed"],
    prerequisites:
      "Elemental Connection (Electric), Novice Focus, Novice Acrobatics",
    frequency: "Static",
    effect: "Choose Static or Electrodash. You gain the Chosen Ability.",
    book: "GoT",
    pageNum: 69,
  },
  {
    name: "Magnetize",
    tags: ["+Speed"],
    prerequisites: "Storm Wizard Rank 1, Adept Acrobatics",
    frequency: "Static",
    effect:
      "You gain the Magnetic Capability and may use this magnetism to stick to surfaces with significant metal content (ex: metal walls obviously, concrete with metal I-beams inside, etc). You may use your Overland to traverse any such surfaces, even if that means walking vertically up a wall or upside down on a ceiling. You may choose not to be Pushed when on such a surface.",
    book: "GoT",
    pageNum: 69,
  },
  {
    name: "Body of Lightning",
    tags: ["+Speed"],
    prerequisites: "Master Acrobatics or Focus",
    frequency: "Static",
    effect: "Choose Volt Absorb or Motor Drive. You gain the Chosen Ability.",
    book: "GoT",
    pageNum: 69,
  },
  {
    name: "Bottled Lightning",
    tags: ["+Speed"],
    prerequisites: "Storm Wizard, Adept Focus",
    frequency: "2 AP - Standard Action ",
    target: "An item made of conductive material",
    effect:
      "Choose one of your Electric Type Moves with a target. You Charge the target item with this Move. Bottled Lightning counts as using the Move for frequency purposes. You may expend this Charge as a Swift Action on your turn to use the Move the item was charged with, originating from the item. If a Pokémon or Trainer touches a Charged item, you may instead activate this Swift Action as if it had the Priority keyword. At the end of a Scene, all items lose their Charge, and you may only have X items Charged at a time where X is half your Focus Rank.",
    book: "GoT",
    pageNum: 69,
  },
  {
    name: "Storm Wizard",
    image: "",
    tags: ["+Speed"],
    frequency: "Static",
    effect:
      "You may learn two Moves from the list below, marked with the Storm Wizard Rank you are gaining or lower.",
    extraFields: {
      "Rank 1 Prerequisites": "Spark Master",
      "Rank 2 Prerequisites": "Expert Acrobatics or Focus",
      "Rank 3 Prerequisites": "Master Acrobatics or Focus",
    },
    book: "GoT",
    pageNum: 69,
  },
  {
    name: "Glamour Weaver",
    tags: ["Class", "+Special Attack"],
    prerequisites:
      "Elemental Connection (Fairy), Novice Charm, Novice Occult Education",
    frequency: "Static",
    effect: "You learn the Moves Sweet Kiss and Disarming Voice.",
    book: "GoT",
    pageNum: 71,
  },
  {
    name: "Fey Law",
    tags: ["+Special Attack"],
    prerequisites: "Glamour Weaver",
    frequency: "1 AP – Swift Action",
    trigger: "You hit a foe with a damaging Fairy attack",
    effect:
      "Choose one of the following: Status-Class, Combat Maneuver, attacks with an unmodified Damage Base 10 or higher, or an Elemental Type. The triggering foe is Bound; they suffer a -X penalty to all rolls made to use attacks with the chosen trait. X is equal to half your Charm or Occult Education Rank. The Bound condition lasts until the end of a Scene. You may unbind someone as a Free Action at any time. A target may not have multiple instances of Bound applied at once.",
    book: "GoT",
    pageNum: 71,
  },
  {
    name: "Passionato Harmony",
    tags: ["+Special Attack"],
    prerequisites: "Glamour Weaver, Expert Charm or Occult Education",
    frequency: "Static",
    effect: "You learn the Moves Dazzling Gleam and Draining Kiss.",
    book: "GoT",
    pageNum: 71,
  },
  {
    name: "Lucky Clover Grand Finale",
    tags: ["+Special Attack"],
    prerequisites: "Passionato Harmony, Master Charm or Occult Education",
    frequency: "Static",
    effect: "You learn the Moves Moonblast and Aromatic Mist.",
    book: "GoT",
    pageNum: 71,
  },
  {
    name: "Magical Burst",
    tags: ["+Special Attack"],
    prerequisites: "Enchanting Transformation, Passionato Harmony",
    frequency: "Scene – Standard Action",
    effect:
      "Use a Glamour Weaver Move as if it had the range Burst 3, Friendly, Exhaust, Smite. All allies within the area-of-effect gain a Tick of Temporary Hit Points or cure themselves of one Volatile Affliction. Enchanting Transformation immediately becomes Unbound, and the AP used to bind it becomes spent instead of becoming available again.",
    extraFields: {
      Condition:
        "You must have Enchanting Transformation Bound to use Magical Burst",
    },
    book: "GoT",
    pageNum: 71,
  },
  {
    name: "Glamour Mastery",
    tags: ["+Special Attack"],
    prerequisites: "4 Glamour Weaver Features",
    frequency: "Static",
    effect: "Choose Magic Guard or Magic Bounce. You gain the Chosen Ability.",
    book: "GoT",
    pageNum: 71,
  },
  {
    name: "Enchanting Transformation",
    tags: ["+Special Attack"],
    prerequisites: "Glamour Weaver",
    frequency: "Bind 2 AP – Shift Action",
    effect:
      "You perform a magical transformation on yourself. While this Feature is Bound, you gain +5 Damage Resistance against Dragon, Fighting, Dark, and Bug-Typed attacks and your Glamour Weaver Moves have the additional effects below.\n\n\n\n»» Sweet Kiss: Sweet Kiss ignores Speed Evasion.\n\n»» Disarming Voice: You may also choose to use Disarming Voice as a Line 4 or Cone 2.\n\n»» Dazzling Gleam: On Even-Numbered rolls, targets hit by Dazzling Gleam have their Accuracy Lowered by 1.\n\n»» Draining Kiss: You gain an additional Tick of Hit Points when gaining Hit Points from Draining Kiss.\n\n»» Moonblast: Whenever Moonblast misses a target, they lose a Tick of Hit Points.\n\n»» Aromatic Mist: All allies affected by Aromatic Mist gain a +2 bonus to their next Save Check.",
    book: "GoT",
    pageNum: 71,
  },
  {
    name: "Fire Bringer",
    tags: ["Class", "+Special Attack or Attack"],
    prerequisites: "Elemental Connection (Fire), Novice Combat",
    frequency: "Static",
    effect:
      "Choose two of Flame Burst, Flame Wheel, Flame Charge, or Will-O-Wisp. You learn the chosen Moves",
    book: "GoT",
    pageNum: 73,
  },
  {
    name: "Fiery Soul",
    tags: ["+Special Attack or Attack"],
    prerequisites: "Fire Bringer",
    frequency: "Static",
    effect:
      "You gain the Heater Capability, and are immune to the Burn condition.",
    book: "GoT",
    pageNum: 73,
  },
  {
    name: "Firebrand",
    tags: ["+Special Attack or Attack"],
    prerequisites: "Fire Bringer, Adept Focus or Combat",
    frequency: "Static",
    effect:
      "Your Fire-Type Moves Burn Targets on a roll of 19+. If a move already has a chance of Burning foes, Firebrand increases the effect range by +2.",
    book: "GoT",
    pageNum: 73,
  },
  {
    name: "Burning Passion",
    tags: ["+Special Attack or Attack"],
    prerequisites: "Fire Bringer, Expert Focus or Combat",
    frequency: "Static",
    effect: "Choose Flash Fire or Flame Body. You gain the chosen Ability.",
    book: "GoT",
    pageNum: 73,
  },
  {
    name: "Blazing Inferno",
    tags: ["+Special Attack or Attack"],
    prerequisites: "Fire Breather Rank 2, Master Focus or Combat",
    frequency: "2 AP – Swift Action",
    effect:
      "You becoming Blazing. While you are Blazing, whenever your Fire-Type Moves Inflict Burn, the Burned target immediately loses a Tick of Hit Points, and loses an additional Combat Stage in Defense. While Blazing, when you hit a foe with a damaging Fire-Type Move, you may choose to automatically burn one target of the Move. If you do, you lose the Blazing Condition after the Move’s effects are resolved.",
    book: "GoT",
    pageNum: 73,
  },
  {
    name: "Fire Breather",
    image: "",
    tags: ["+Special Attack or Attack"],
    frequency: "Static",
    effect:
      "Learn two Fire Breather Moves from the list. You may choose any Move marked with the Fire Breather Rank you are taking or lower.",
    extraFields: {
      "Rank 1 Prerequisites": "Expert Focus or Combat",
      "Rank 2 Prerequisites": "Master Focus or Combat",
    },
    book: "GoT",
    pageNum: 73,
  },
  {
    name: "Wind Runner",
    tags: ["Class", "+Speed"],
    prerequisites:
      "Elemental Connection (Flying), Novice Acrobatics, Novice Perception",
    frequency: "Static",
    effect:
      "You gain the Levitate Ability. You have a total Levitate Speed equal to 4 plus half of the higher of your Acrobatics or Perception Rank.",
    book: "GoT",
    pageNum: 75,
  },
  {
    name: "One With the Winds",
    tags: ["+Speed"],
    prerequisites: "Adept Perception",
    frequency: "Bind 2 AP – Standard Action",
    effect:
      "You summon a windy breeze that follows you around. Your sense of touch is extended through this wind, and you can guide it by thought, using it to perceive the shape and texture of objects as long as the wind can reach, even through very small cracks and holes. The range of this effect is equal to your Acrobatics Rank plus Perception Rank in meters.",
    book: "GoT",
    pageNum: 75,
  },
  {
    name: "Flight",
    tags: ["+Speed"],
    prerequisites: "One With the Winds, Adept Acrobatics",
    frequency: "1 AP – Swift Action",
    effect:
      "You gain a Sky Speed equal to your Levitate Speed plus your Acrobatics or Perception Rank for the remainder of the round.",
    book: "GoT",
    pageNum: 75,
  },
  {
    name: "Gale Speed",
    tags: ["+Speed"],
    prerequisites: "Raging Winds Rank 1, Master Acrobatics or Perception",
    frequency: "Static",
    effect: "Choose Celebrate or Gale Wings. You gain the chosen Ability.",
    book: "GoT",
    pageNum: 75,
  },
  {
    name: "Raging Winds",
    image: "",
    tags: ["Ranked 3", "+Speed"],
    prerequisites: "Wind Runner",
    frequency: "Static",
    effect:
      "You may learn two Moves from the list, marked with the Raging Winds Rank you are gaining or lower.",
    extraFields: {
      "Rank 1 Prerequisites": "Wind Runner",
      "Rank 2 Prerequisites": "Expert Acrobatics or Perception",
      "Rank 3 Prerequisites": "Master Acrobatics or Perception",
    },
    book: "GoT",
    pageNum: 75,
  },
  {
    name: "Apparition",
    tags: ["Class", "+Attack", "Weapon"],
    prerequisites:
      "Elemental Connection (Ghost), Novice Intimidate, Novice Occult Education",
    frequency: "Static",
    effect:
      "When wielding Melee Weapons, you may use Occult Education or Intimidate instead of Combat to determine the Damage Base of your Struggle Attacks, to resist Disarm Maneuvers, and to qualify for a Weapon’s Moves. Your Weapon Attacks always treat you as having the Reach Capability, and foes may not activate Reaction effects against them that specify being hit by a Melee Attack.",
    book: "GoT",
    pageNum: 77,
  },
  {
    name: "Shadow Arms",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Apparition",
    frequency: "Static",
    effect:
      "You learn the Moves Shadow Punch and Shadow Sneak. You may use these as Weapon Attacks when wielding Melee Weapons.",
    book: "GoT",
    pageNum: 77,
  },
  {
    name: "Shadow Form",
    tags: ["+Attack"],
    prerequisites: "Silent Assasin, Expert Intimidate or Occult Education",
    frequency: "Bind 2 AP – Swift Action",
    effect:
      "While this Feature is Bound, your appearance becomes wan and obviously otherworldly. Your natural Weaknesses, Resistances, and Immunities change to match that of the Ghost Type. Additionally, while in Shadow Form, you are immune to the Cursed Status (if you were previously Cursed, you are instantly cured upon going into Shadow Form) and gain the Phasing Capability. You may unbind this Feature as a Swift Action, returning to your normal appearance.",
    book: "GoT",
    pageNum: 77,
  },
  {
    name: "Too Spooky",
    tags: ["+Attack"],
    prerequisites: "Apparition",
    frequency: "Static",
    effect: "Choose Pressure or Frighten. You gain the chosen Ability.",
    book: "GoT",
    pageNum: 77,
  },
  {
    name: "Silent Assassin",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Apparition, Adept Intimidate or Occult Education",
    frequency: "Bind 2 AP – Standard Action",
    effect:
      "While this Feature is Bound, your Struggle Attacks and Weapon Attacks deal Ghost-Type Damage, and you gain the Dead Silent Capability.",
    book: "GoT",
    pageNum: 77,
  },
  {
    name: "Haunted Wounds",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Shadow Arms, Master Intimidate or Occult Education",
    frequency: "Scene x2 – Free Action",
    trigger: "You hit with an Apparition Move or Ghost-Typed Weapon Attack",
    effect:
      "After one full round, repeat the triggering attack against one target as a Free Action, regardless of range. If this attack hits, it deals damage as if it were resisted one step further. Haunted Wounds may only affect a target once per Scene.",
    book: "GoT",
    pageNum: 77,
  },
  {
    name: "Phantom Menace",
    tags: ["+Attack", "Weapon"],
    prerequisites: "Shadow Arms, Expert Intimidate or Occult Education",
    frequency: "Static",
    effect:
      "You gain the Moves Shadow Claw and Phantom Force. You may use these Moves as Weapon Attacks when wielding Melee Weapons.",
    book: "GoT",
    pageNum: 77,
  },
  {
    name: "Druid",
    image: "",
    tags: ["Class", "Special"],
    prerequisites:
      "Elemental Connection (Grass), Novice Survival, Novice General Education",
    frequency: "Static",
    effect:
      "Your powers begin to take after either Flowers, Fungi, or Trees. Depending on your oath, you gain an Ability and Stat Tags. Whenever you gain a Druid Feature, you gain the same Stat Tags.",
    book: "GoT",
    pageNum: 79,
  },
  {
    name: "Green Path",
    tags: ["Special"],
    prerequisites: "Druid",
    frequency: "Static",
    effect:
      "You gain the Naturewalk (Grassland) and Naturewalk (Forest) capabilities, and you are immune to Moves with the Powder keyword.",
    book: "GoT",
    pageNum: 79,
  },
  {
    name: "Overgrowth",
    tags: ["Special"],
    prerequisites: "Nature's Embrace Rank 3",
    frequency: "2 AP – Swift Action ",
    trigger: "You hit with a Druid Move",
    effect:
      "One target of the triggering Move is afflicted with Overgrowth. As long as the target is afflicted, they are one step less Resistant to Grass-Type attacks, to a maximum of neutral damage, and they cannot recover Hit Points or gain Temporary Hit Points. Whenever they would do so, you gain those Hit Points or Temporary Hit Points instead. Overgrowth is removed when the target Takes a Breather or is hit by a damaging Fire, Ice, Poison, Flying, or Bug-Type attack. Overgrowth may only affect a target once per Scene.",
    book: "GoT",
    pageNum: 79,
  },
  {
    name: "Druid's Call",
    tags: ["Special"],
    prerequisites: "Green Path",
    frequency: "Scene x2 – Standard Action ",
    effect:
      "6 small saplings, flowery bushes, or mushroom patches (depending on your oath) suddenly grow within 6 meters of you, occupying 1 square each. This vegetation lasts until the end of the encounter, and acts as rough terrain that blocks line of sight for Pokémon and Trainers without the Naturewalk (Forest) Capability. Whenever you use a Move learned through Nature's Embrace, you may have it originate from these Plants as if they were the user. This Feature must be used on soil, or terrain under which soil is hidden by only a few inches (such as most sidewalks, parking lots, gravel or woodchip lots, etc.)",
    book: "GoT",
    pageNum: 79,
  },
  {
    name: "Nature's Embrace",
    image: "",
    tags: ["Special", "Ranked 3"],
    prerequisites: "Druid",
    frequency: "Static",
    effect:
      "You learn 2 Moves chosen from the list below, marked with the Rank of this Feature you are gaining or lower. Moves marked with an Oath require that Oath to be chosen.",
    extraFields: {
      "Rank 1 Prerequisites": "Druid",
      "Rank 2 Prerequisites": "Adept Survival or General Education",
      "Rank 3 Prerequisites": "Expert Survival or General Education",
    },
    book: "GoT",
    pageNum: 79,
  },
  {
    name: "Earth Shaker",
    tags: ["Class", "+Defense"],
    prerequisites:
      "Elemental Connection (Ground), Novice Intuition, Novice Focus",
    frequency: "Static",
    effect:
      "Pick two of Bulldoze, Mud Shot, or Sand-Attack. You learn the chosen Moves.",
    book: "GoT",
    pageNum: 81,
  },
  {
    name: "Earthen Bond",
    tags: ["+Defense"],
    prerequisites: "Earth Shaker",
    frequency: "Static",
    effect:
      "You gain the Tremorsense Capability, and you gain Naturewalk for Cave, Mountain and Desert.",
    book: "GoT",
    pageNum: 81,
  },
  {
    name: "Earth Mother's Blessing",
    tags: ["Ranked 2", "+Defense"],
    frequency: "Static",
    effect:
      "Each Rank, choose one of Arena Trap or Lightningrod. You gain the chosen Ability.",
    extraFields: {
      "Rank 1 Prerequisites": "Adept Focus or Intuition",
      "Rank 2 Prerequisites": "Ground Out, Master Focus or Intuition",
    },
    book: "GoT",
    pageNum: 81,
  },
  {
    name: "Earthshifter",
    tags: ["+Defense"],
    prerequisites: "Ground Out",
    frequency: "2 AP – Swift Action",
    trigger: "You hit with a damaging Ground Type Move",
    effect:
      "You initiate a Trip Maneuver against 1 target of the Move. The Maneuver automatically hits, and you may use your Focus or Intuition for the opposed check.",
    book: "GoT",
    pageNum: 81,
  },
  {
    name: "Ground Out",
    tags: ["+Defense"],
    prerequisites: "Earth Shaker, Expert Focus or Intuition",
    frequency: "Static",
    effect:
      "Pick two of Drill Run, Magnitude, or Mud Bomb. You learn the chosen Moves",
    book: "GoT",
    pageNum: 81,
  },
  {
    name: "Tectonic Shift",
    tags: ["+Defense"],
    prerequisites: "Ground Out, Master Focus or Intuition",
    frequency: "Static",
    effect:
      "Pick two of Earthquake, Earth Power, or Sand Tomb. You learn the chosen Moves",
    book: "GoT",
    pageNum: 81,
  },
  {
    name: "Frost Touched",
    tags: ["Class", "+Attack or Special Attack"],
    prerequisites:
      "Elemental Connection (Ice), Novice Athletics, Novice Survival",
    frequency: "Static",
    effect:
      "Choose two out of Haze, Ice Shard, Mist, and Powder Snow. You learn the Chosen Moves.",
    book: "GoT",
    pageNum: 83,
  },
  {
    name: "The Cold Never Bothered Me Anyway",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Frost Touched",
    frequency: "Static",
    effect:
      "You gain the Naturewalk (Tundra) Capability, are immune to being Frozen, and do not lose Hit Points from Hail.",
    book: "GoT",
    pageNum: 83,
  },
  {
    name: "Frozen Domain",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Expert Athletics or Survival",
    frequency: "2 AP – Standard Action ",
    effect:
      "Set 6 square meters of Frozen Domain within range 6. All 6 meters must be adjacent with at least one other space of Frozen Domain. All legal targets passing through these squares must make an Acrobatics check with a DC equal to 4 + twice your Survival Rank. On failure, the target is Tripped. Pokémon who are flying, levitating, or have the Naturewalk (Tundra) Capability are immune to this effect. When standing on a square affected by Frozen Domain, you may act as if you were in Hail weather. When a Fire-Type attack originates from or targets a square of Frozen Domain, that square of Frozen Domain melts and is cleared. Frozen Domain is considered a Hazard.",
    book: "GoT",
    pageNum: 83,
  },
  {
    name: "Winter is Coming",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Master Athletics or Survival",
    frequency: "Static",
    effect: "You gain the Frostbite Ability",
    book: "GoT",
    pageNum: 83,
  },
  {
    name: "Glacial Defense",
    tags: ["+Attack or Special Attack"],
    prerequisites: "Frost Touched",
    frequency: "Static",
    effect: "Choose Ice Shield or Winter's Kiss. You gain the Chosen Ability.",
    book: "GoT",
    pageNum: 83,
  },
  {
    name: "Winter’s Herald",
    image: "",
    tags: ["Ranked 2", "+Attack or Special Attack"],
    prerequisites: "Expert Athletics or Survival",
    frequency: "Static",
    effect:
      "You may learn two Moves from the list below, marked with the Rank of Winter's Herald you are gaining or lower.",
    extraFields: {
      "Rank 1 Prerequisites": "Expert Athletics or Survival",
      "Rank 2 Prerequisites": "Master Athletics or Survival",
    },
    book: "GoT",
    pageNum: 83,
  },
  {
    name: "Prism",
    tags: ["Class", "+Special Attack"],
    prerequisites:
      "Elemental Connection (Normal), Novice General Education, Novice Charm",
    frequency: "Static",
    effect: "You learn the Moves Flash and Swift.",
    book: "GoT",
    pageNum: 85,
  },
  {
    name: "Blinding Brightness",
    tags: ["+Special Attack"],
    prerequisites: "Prism",
    frequency: "Static",
    effect: "You gain the Illuminate Ability.",
    book: "GoT",
    pageNum: 85,
  },
  {
    name: "Sparkle",
    tags: ["+Special Attack"],
    prerequisites: "Prism, Expert Charm or General Education",
    frequency: "Static",
    effect: "You learn the Moves Tri-Attack and Weather Ball.",
    book: "GoT",
    pageNum: 85,
  },
  {
    name: "Rainbow Surge",
    tags: ["+Special Attack"],
    prerequisites: "Sparkle, Master Charm or General Education",
    frequency: "Static",
    effect: "You learn the Moves Hyper Beam and Morning Sun.",
    book: "GoT",
    pageNum: 85,
  },
  {
    name: "Lucent Mirage",
    tags: ["+Special Attack"],
    prerequisites: "Prism",
    frequency: "Static",
    effect: "You gain the Illusionist Capability.",
    book: "GoT",
    pageNum: 85,
  },
  {
    name: "Prismatic Alignment",
    tags: ["+Special Attack"],
    prerequisites: "4 Prism Features, Master Charm or General Education",
    frequency: "2 AP – Swift Action",
    trigger: "You use a Prism Move",
    effect:
      "The effect of this Feature depends on the Triggering Move. You may only use Prismatic Alignment with each Move once per Scene.\n\n\n\n»» Flash: Flash also Blinds all targets it hits until the end of their next turn.\n\n»» Swift: Swift instead has a range of 8, 3 Targets.\n\n»» Tri Attack: Roll twice for Tri Attack’s Accuracy Roll and take the better result. If you trigger its Effect Range, you may choose the effect instead of rolling for it.\n\n»» Weather Ball: You use Weather Ball as if you were in the Weather of your choice.\n\n»» Hyper Beam: Hyper Beam instead has a Range of Burst 2, Smite or 10, Ranged Blast 3, Smite.\n\n»» Morning Sun: You use Morning Sun as if you were in Sunny Weather, and you may cure yourself of one Status Affliction.",
    book: "GoT",
    pageNum: 85,
  },
  {
    name: "Luminous Aura",
    tags: ["+Special Attack"],
    prerequisites: "Blinding Brightness, Adept Charm or General Education",
    frequency: "Static",
    effect: "Choose Starlight or Sunglow. You gain the Chosen Ability.",
    book: "GoT",
    pageNum: 85,
  },
  {
    name: "Miasmic",
    tags: ["Class", "+Defense"],
    prerequisites:
      "Elemental Connection (Poison), Novice Stealth, Novice Guile",
    frequency: "Static",
    effect: "You learn the Moves Acid and Clear Smog.",
    book: "GoT",
    pageNum: 87,
  },
  {
    name: "Corrupt Blood",
    tags: ["+Defense"],
    prerequisites: "Miasmic",
    frequency: "Static",
    effect:
      "You are immune to the Poisoned and Badly Poisoned statuses and resist Poison-type attacks one step further.",
    book: "GoT",
    pageNum: 87,
  },
  {
    name: "Flexible Form",
    tags: ["+Defense"],
    prerequisites: "Miasmic",
    frequency: "Static",
    effect:
      "Your body becomes more malleable, and even your bones are able to flex when required. You do not gain Wounds from taking Massive damage, and you gain a +2 Bonus to any Acrobatics or Athletics Check made to bend, squeeze, or otherwise contort your body - including those to avoid Trip or Grapple maneuvers.",
    book: "GoT",
    pageNum: 87,
  },
  {
    name: "Vile Body",
    tags: ["+Defense"],
    prerequisites: "Adept Guile or Stealth",
    frequency: "Static",
    effect:
      "Choose Absorb Force, Poison Point, or Poison Touch. You gain the chosen Ability.",
    book: "GoT",
    pageNum: 87,
  },
  {
    name: "Miasma’s Call",
    tags: ["+Defense"],
    prerequisites: "Vile Body, Expert Stealth or Guile",
    frequency: "Static",
    effect: "You learn the moves Acid Armor and Sludge Bomb.",
    book: "GoT",
    pageNum: 87,
  },
  {
    name: "Miasma Unleashed",
    tags: ["+Defense"],
    prerequisites: "Miasma’s Call, Master Stealth or Guile",
    frequency: "Static",
    effect: "You learn the moves Sludge Wave and Toxic.",
    book: "GoT",
    pageNum: 87,
  },
  {
    name: "Miasmic Spray",
    tags: ["+Defense"],
    prerequisites: "Miasma’s Call, Master Stealth or Guile",
    frequency: "2 AP – Swift Action",
    trigger:
      "You hit with Acid, Clear Smog, Sludge Bomb, Sludge Wave, or Toxic; or use Acid Armor",
    effect:
      "The Effect of this feature depends on the triggering move.\n\nAcid:  Instead of its usual effect, Acid lowers the Special Defense of all targets hit by -2 Combat Stages.\n\nClear Smog:  Clear Smog’s target loses 5 HP for each combat stage lost.\n\nSludge Bomb:  The Target receives a -3 penalty to Accuracy Rolls until the end of your next turn.\n\nSludge Wave:  All targets in Sludge Wave's Burst are Slowed until the end of their next turn.\n\nToxic:  The target's Badly Poison Hit Point Loss begins at 10 instead of 5.\n\nAcid Armor:  You are not slowed while liquefied and resist all special damage one step.",
    book: "GoT",
    pageNum: 87,
  },
  {
    name: "Stone Warrior",
    tags: ["Class", "+Defense"],
    prerequisites:
      "Elemental Connection (Rock), Novice Combat, Novice Survival",
    frequency: "Static",
    effect: "You learn the Moves Rock Tomb and Wide Guard.",
    book: "GoT",
    pageNum: 89,
  },
  {
    name: "Stone Stance",
    tags: ["+Defense"],
    prerequisites: "Stone Warrior",
    frequency: "Bind 2 AP – Standard Action",
    effect:
      "You adopt one of the stances below, gaining the effects of the stance while this Feature remains bound. You may switch your active Stance as a Standard Action without rebinding your AP. The benefits from this Feature do not apply if you are not standing on a solid surface, such as deep mud or snow, or if you are outright swimming or even flying.\n\n\n\n• Falling Boulder Stance: You gain a +5 bonus to all Damage Rolls, but lose 5 HP from Recoil whenever you hit with an attack.\n\n• Moon Mountain Stance: Your initiative is lowered by -5, but you gain 5 Damage Reduction and are immune to Push or Pull effects.\n\n• Roiling Earth Stance: After a successful Intercept action, you may make a Struggle Attack against a foe within range.",
    book: "GoT",
    pageNum: 89,
  },
  {
    name: "Rock Power",
    tags: ["Ranked 2", "+Defense"],
    frequency: "Static",
    effect:
      "Each Rank, choose one of Sturdy, Rock Head, Run Up, or Sand Veil. You gain the chosen Ability. If you choose Sand Veil, you may consider sand a “solid surface” for the purposes of Stone Stance.",
    extraFields: {
      "Rank 1 Prerequisites": "Adept Combat or Survival",
      "Rank 2 Prerequisites": "Expert Combat or Survival",
    },
    book: "GoT",
    pageNum: 89,
  },
  {
    name: "Shards of Stone",
    tags: ["+Defense"],
    prerequisites: "Expert Combat or Survival",
    frequency: "Static",
    effect: "You learn the Moves Rock Slide and Stealth Rock",
    book: "GoT",
    pageNum: 89,
  },
  {
    name: "Stone Cold Finish",
    tags: ["+Defense"],
    prerequisites: "Shards of Stone, Master Combat or Survival",
    frequency: "Static",
    effect: "You learn the Moves Stone Edge and Head Smash",
    book: "GoT",
    pageNum: 89,
  },
  {
    name: "Stone Stance Mastery",
    tags: ["+Defense"],
    prerequisites: "Stone Stance, Master Combat or Survival",
    frequency: "Static",
    effect:
      "Whenever you bind Stone Stance, you may choose two Stances and apply the effects of both.",
    book: "GoT",
    pageNum: 89,
  },
  {
    name: "Steelheart",
    tags: ["Class", "+Defense", "Weapon"],
    prerequisites:
      "Elemental Connection (Steel), Novice Athletics, Novice Focus",
    frequency: "Static",
    effect:
      "When wielding metal Melee Weapons, you may use Athletics or Focus instead of Combat to determine the Damage Base of your Struggle Attacks, to qualify for a Weapon’s Moves, and to resist Disarm Checks. Whenever your Weapon Attacks hit a foe who has previously hit you with a Melee attack in the same round, the foe loses a Tick of Hit Points.",
    book: "GoT",
    pageNum: 91,
  },
  {
    name: "Champion of Steel",
    tags: ["+Defense", "Weapon"],
    prerequisites: "Steelheart",
    frequency: "1 AP – Free Action",
    trigger: "You make a Weapon Attack.",
    effect:
      "The attack or Move increases your Defense by 1 Combat Stage on 16+ and you may have it deal Steel-Type Damage if you wish.",
    book: "GoT",
    pageNum: 91,
  },
  {
    name: "Steel Wind",
    tags: ["+Defense", "Weapon"],
    prerequisites: "Steelheart",
    frequency: "Static",
    effect:
      "You learn the Moves Bullet Punch and Metal Claw. You may use these Moves as Weapon Attacks when wielding Melee Weapons.",
    book: "GoT",
    pageNum: 91,
  },
  {
    name: "Reactive Armour",
    tags: ["+Defense"],
    prerequisites: "Steelheart, Adept Athletics or Focus",
    frequency: "Scene x2 – Free Action",
    trigger:
      "You gain an Injury or take a Critical Hit while wearing metallic Armor",
    effect:
      "All foes within a Burst 1 lose Hit Points equal to double your Athletics or Focus Rank, and you gain Damage Reduction equal to double your Athletics or Focus Rank for one full round.",
    book: "GoT",
    pageNum: 91,
  },
  {
    name: "Impenetrable",
    tags: ["+Defense"],
    prerequisites: "Steelheart, Expert Athletics or Focus",
    frequency: "Static",
    effect: "You gain the Bulletproof Ability.",
    book: "GoT",
    pageNum: 91,
  },
  {
    name: "Master of Arms",
    tags: ["+Defense", "Weapon"],
    prerequisites: "Steelheart, Expert Athletics or Focus",
    frequency: "Static",
    effect: "You learn the Call to Arms and Unlimited Steel Works Talents.",
    seeAlso: ["Call to Arms", "Unlimited Steel Works"],
    book: "GoT",
    pageNum: 91,
  },
  {
    name: "Man of Steel",
    tags: ["+Defense", "Weapon"],
    prerequisites: "Steelheart, Master Athletics or Focus",
    frequency: "Static",
    effect:
      "You learn the Moves Meteor Mash and King’s Shield. You may use these Moves as Weapon Attacks when wielding Melee Weapons.",
    book: "GoT",
    pageNum: 91,
  },
  {
    name: "Maelstrom",
    tags: ["Class", "+Speed"],
    prerequisites:
      "Elemental Connection (Water), Novice Athletics, Novice Acrobatics",
    frequency: "Static",
    effect:
      "You gain the Gilled Capability, and a +2 bonus to your Swim speed. Whenever your Water-Type Moves miss all targets, you gain a Tick of Temporary Hit Points.",
    book: "GoT",
    pageNum: 93,
  },
  {
    name: "Water's Shroud",
    tags: ["+Speed"],
    prerequisites: "Call the Current Rank 2",
    frequency: "Static",
    effect: "Choose Wash Away or Storm Drain. You gain the Chosen Ability.",
    book: "GoT",
    pageNum: 93,
  },
  {
    name: "Hydro Jet",
    tags: ["+Speed"],
    prerequisites: "Call the Current Rank 1",
    frequency: "1 AP – Free Action",
    trigger: "You use a damaging single target Water-Type Move",
    effect:
      "Hydro Jet’s effect depends on if the triggering Move was Melee or Ranged.\n\n\n\n»» If Melee, the Move gains the Pass keyword and you may change direction during the four meters of Pass (but may still only target any given Pokémon or Trainer once).\n\n»» If Ranged, the Move becomes a Line 4 instead of its usual range.",
    book: "GoT",
    pageNum: 93,
  },
  {
    name: "Oceanic Feeling",
    tags: ["+Speed"],
    prerequisites: "Water's Shroud, Master Athletics or Acrobatics",
    frequency: "Scene x2 – Free Action",
    effect:
      "You may activate Oceanic Feeling when either Wash Away or Storm Drain would be triggered to gain that Ability for 1 full round, if you do not already have it, and immediately Trigger it. Activating an Ability this way ignores its usual Frequency. You may use each Ability once per Scene this way.",
    book: "GoT",
    pageNum: 93,
  },
  {
    name: "Call the Current",
    image: "",
    tags: ["Ranked 3", "+Speed"],
    frequency: "Static",
    effect:
      "You learn 2 Moves chosen from the list, marked with the Rank of this Feature you are gaining or lower.",
    extraFields: {
      "Rank 1 Prerequisites": "Maelstrom",
      "Rank 2 Prerequisites": "Adept Athletics or Acrobatics",
      "Rank 3 Prerequisites": "Expert Athletics or Acrobatics",
    },
    book: "GoT",
    pageNum: 93,
  },
];

export default got;
